version: '3.9'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./cert/:/home/cert/
      - ./home_page/:/home/home_page/
      - ./config/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
    networks:
      - sso  
  sso:
    build: 
      context: keycloak/.
    container_name: sso
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
    environment:
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=true
      - SERVER_PORT=8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_PROXY=edge
      - KC_HOSTNAME_URL=https://localhost/sso
      - KC_HOSTNAME_ADMIN_URL=https://localhost/sso
    entrypoint: "/opt/keycloak/bin/kc.sh -v start --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false --optimized"
    networks:
      - sso
networks:
  sso: